############
###  ZSH  ###
#############
#
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/martin/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh
# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

####################
###  END OF ZSH  ###
####################

###########
### NVM ###
###########
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

function grepr() {
	grep -rin $@
}

function mkdircd ()
{
    mkdir -p -- "$1" &&
      cd -P -- "$1"
}

function cdc() {
	cd *$1*
}

function gacp() {
	git add . && git commit -m \""$@"\" && git push
}

function ffc() {
	. ff "$@" -cmd=cd
}

export PATH=$PATH:~/.tools  # Add tools directory to path
export PATH=$PATH:/home/martin/u++-7.0.0/bin
export PATH=/usr/local/texlive/2019/bin/x86_64-linux:$PATH
export PATH=$PATH:/usr/local/go/bin

alias ..='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ..5='cd ../../../../..'
alias ..6='cd ../../../../../..'
alias ..7='cd ../../../../../../..'
alias prof='vim ~/.zshrc'
alias profs='source ~/.zshrc'
alias vimrc='vim ~/.vimrc'
alias gs='git status'
alias gpom='git pull origin master'
alias jn='jupyter notebook'
alias lsmb='ls -l --block-size=M'

# Machine specific aliases
# alias openhere="gvfs-open ."
alias openhere="nautilus ."
alias work="cd /media/martin/SAMSUNG_860_EVO/Work"
alias prog="cd /media/martin/SAMSUNG_860_EVO/Programming"
alias dls='xdg-open "/home/martin/Downloads"'
alias cs246='cd "/media/martin/SAMSUNG_860_EVO/Work/2A/{CS 246}"'
alias uwlogin='ssh -Y "mkflui@linux.student.cs.uwaterloo.ca"'
alias uwlogin2='ssh -Y "mkflui@ubuntu1804-002.student.cs.uwaterloo.ca"'
alias uwlogin4='ssh -Y "mkflui@ubuntu1804-004.student.cs.uwaterloo.ca"'
alias uwlogin6='ssh -Y "mkflui@ubuntu1804-006.student.cs.uwaterloo.ca"'
alias uwlogin8='ssh -Y "mkflui@ubuntu1804-008.student.cs.uwaterloo.ca"'
alias ugster='ssh mkflui@ugster05.student.cs.uwaterloo.ca'
alias valgrindf='valgrind --leak-check=full '

# Work folder shortcuts
WORK="/media/martin/SAMSUNG_860_EVO/Work"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Reference
REF="/media/martin/SAMSUNG_860_EVO/Programming/Reference"
alias pyhelp='vim "$REF/python_notes.md"'
alias vimhelp='vim "$REF/vim_notes.txt"'
alias bashhelp='vim "$REF/bash_notes.txt"'

# Shift+ctrl+drag to create link
# Fix VirtualBox 
# $ sudo -i
# $ cd  '/root/module_signing'
# $ ./sign-vbox-modules
# $ modprobe vboxdrv

